#++++++++++++++++++++++++++++++++++++++
# Redis Docker container
#++++++++++++++++++++++++++++++++++++++
#
# Official images:
#
#   redis - official Redis
#           https://hub.docker.com/r/library/redis/
#
#++++++++++++++++++++++++++++++++++++++

FROM redis

#RUN mkdir /data/redis && chown redis:redis /data/redis
#VOLUME /data/redis
#WORKDIR /data/redis
