#######################################
# Environment Configuration
#  - feel free to edit -
# -> for most changes you only have to
#         docker-compose up -d
#    to apply them
#######################################

#######################################
# PHP Debugger (xdebug|blackfire|none)

PHP_DEBUGGER=xdebug

#######################################
# Context environment

# TYPO3
#TYPO3_CONTEXT=Development/Docker

# Symfony
#SYMFONY_ENV=dev
#SYMFONY_DEBUG=0

# CakePHP
#CAKE_ENV=dev

# yii
#YII_ENVIRONMENT=Development

# Laravel
LARAVEL_ENV=development

APP_NAME=Bitcoin
APP_ENV=local
APP_KEY=base64:7S2BwwvEjAZEYPwjFb7cgU6DvKTooFjzSGDJI/wK2a4=
APP_LOG_LEVEL=debug
APP_URL=http://laravel.adminlte.localhost

APP_DEBUG=true
DEBUGBAR_ENABLED=true

DB_CONNECTION=mysql
#DB_CONNECTION=sqlite
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=adminlte
DB_USERNAME=dev
DB_PASSWORD=dev

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

#REDIS_HOST=127.0.0.1
#REDIS_PASSWORD=null
#REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

GITHUB_OAUTH_APP_ID=3a74561cb85f4ce181a4
GITHUB_OAUTH_APP_SECRET=858f093d253352de65d5ddf7ba428e248f4ecaab
GITHUB_OAUTH_APP_REDIRECT_URL=http://laravel.adminlte.localhost/auth/github/callback
